import type { Palindrome } from './types';

export const normalizePalindrome = (value: string) =>
  value.toLowerCase().replace(/[^a-z0-9]/g, ``);

export const palindromes: readonly Palindrome[] = [
  {
    letters: 5,
    votes: 0,
    comments: 0,
    id: `level`,
    text: `level`,
    type: `word`,
    language: `English`,
    added: `2026-10-06`,
    addedBy: `Palindrome Lists`,
    author: `Not recorded`,
    firstRecorded: `Not recorded`,
    source: `Editorial example`,
  },
  {
    letters: 14,
    votes: 0,
    comments: 0,
    type: `phrase`,
    language: `English`,
    added: `2026-10-06`,
    addedBy: `Palindrome Lists`,
    author: `Not recorded`,
    id: `never-odd-or-even`,
    text: `Never odd or even.`,
    firstRecorded: `Not recorded`,
    source: `Editorial example`,
  },
  {
    letters: 7,
    votes: 0,
    comments: 0,
    type: `word`,
    id: `racecar`,
    text: `racecar`,
    language: `English`,
    added: `2026-10-06`,
    addedBy: `Palindrome Lists`,
    author: `Not recorded`,
    firstRecorded: `Not recorded`,
    source: `Editorial example`,
  },
  {
    votes: 0,
    letters: 19,
    comments: 0,
    type: `phrase`,
    language: `English`,
    added: `2026-10-06`,
    addedBy: `Palindrome Lists`,
    author: `Not recorded`,
    firstRecorded: `Not recorded`,
    source: `Editorial example`,
    id: `was-it-a-car-or-a-cat-i-saw`,
    text: `Was it a car or a cat I saw?`,
  },
  {
    letters: 5,
    votes: 0,
    comments: 0,
    id: `civic`,
    text: `civic`,
    type: `word`,
    language: `English`,
    added: `2026-10-06`,
    addedBy: `Palindrome Lists`,
    author: `Not recorded`,
    firstRecorded: `Not recorded`,
    source: `Editorial example`,
  },
  {
    letters: 5,
    votes: 0,
    comments: 0,
    id: `radar`,
    text: `radar`,
    type: `word`,
    language: `English`,
    added: `2026-10-06`,
    addedBy: `Palindrome Lists`,
    author: `Not recorded`,
    firstRecorded: `Not recorded`,
    source: `Editorial example`,
  },
  {
    votes: 0,
    letters: 4,
    comments: 0,
    id: `anna`,
    text: `Anna`,
    type: `name`,
    language: `English`,
    added: `2026-10-06`,
    addedBy: `Palindrome Lists`,
    author: `Not recorded`,
    firstRecorded: `Not recorded`,
    source: `Editorial example`,
  },
  {
    votes: 0,
    letters: 3,
    comments: 0,
    id: `ada`,
    text: `Ada`,
    type: `name`,
    language: `English`,
    added: `2026-10-06`,
    addedBy: `Palindrome Lists`,
    author: `Not recorded`,
    firstRecorded: `Not recorded`,
    source: `Editorial example`,
  },
];
