export const phraseExamples = [
  { text: `Step on no pets.`, source: `Editorial example` },
  { text: `No lemon, no melon.`, source: `Editorial example` },
  { text: `Madam, I'm Adam.`, source: `Editorial example` },
  { text: `A man, a plan, a canal: Panama!`, source: `Editorial example` },
  { text: `Able was I ere I saw Elba.`, source: `Editorial example` },
  { text: `Do geese see God?`, source: `Editorial example` },
  { text: `Live not on evil.`, source: `Editorial example` },
  { text: `Don't nod.`, source: `Editorial example` },
  { text: `A Santa at NASA.`, source: `Editorial example` },
  { text: `A dog! A panic in a pagoda!`, source: `Editorial example` },
  { text: `Borrow or rob?`, source: `Editorial example` },
  { text: `Bird rib.`, source: `Editorial example` },
  { text: `Drawn inward.`, source: `Editorial example` },
  { text: `Dump mud.`, source: `Editorial example` },
  { text: `Go, dog!`, source: `Editorial example` },
  { text: `I did, did I?`, source: `Editorial example` },
  { text: `I prefer pi.`, source: `Editorial example` },
  { text: `Lepers repel.`, source: `Editorial example` },
  { text: `Ma has a ham.`, source: `Editorial example` },
  { text: `My gym.`, source: `Editorial example` },
  { text: `Now I won.`, source: `Editorial example` },
  { text: `Nurses run.`, source: `Editorial example` },
  { text: `Pull up if I pull up.`, source: `Editorial example` },
  { text: `Top spot.`, source: `Editorial example` },
  { text: `Tuna nut.`, source: `Editorial example` },
  { text: `Was it a cat I saw?`, source: `Editorial example` },
  { text: `A Toyota.`, source: `Editorial example` },
  { text: `A Toyota's a Toyota.`, source: `Editorial example` },
  { text: `A Toyota, race fast, safe car, a Toyota.`, source: `Editorial example` },
  { text: `A tin mug for a jar of gum, Nita.`, source: `Editorial example` },
  { text: `Bald elf fled lab.`, source: `Editorial example` },
  { text: `Bosses sob.`, source: `Editorial example` },
  { text: `Camp Mac.`, source: `Editorial example` },
  { text: `Dee saw a seed.`, source: `Editorial example` },
  { text: `Delia sailed.`, source: `Editorial example` },
  { text: `Delia sailed, Eva waved, Elias ailed.`, source: `Editorial example` },
  { text: `Did Hannah say as Hannah did?`, source: `Editorial example` },
  { text: `Did Dean aid Diana? Ed did.`, source: `Editorial example` },
  { text: `Did I draw Della too tall, Edward? I did!`, source: `Editorial example` },
  { text: `Do nine men interpret? Nine men, I nod.`, source: `Editorial example` },
  { text: `Don did nod.`, source: `Editorial example` },
  { text: `Drab as a fool, aloof as a bard.`, source: `Editorial example` },
  { text: `Draw, O coward!`, source: `Editorial example` },
  { text: `Dumb mud.`, source: `Editorial example` },
  { text: `Ed is loopy poolside.`, source: `Editorial example` },
  { text: `Elim saw a smile.`, source: `Editorial example` },
  { text: `Elk rap song? No sparkle.`, source: `Editorial example` },
  { text: `Emil saw a slime.`, source: `Editorial example` },
  { text: `Enid and Edna dine.`, source: `Editorial example` },
  { text: `Euston saw I was not Sue.`, source: `Editorial example` },
  { text: `Evil, all its sin is still alive.`, source: `Editorial example` },
  { text: `Flee to me, remote elf.`, source: `Editorial example` },
  { text: `Gate tag.`, source: `Editorial example` },
  { text: `I led some to Hot Emo's deli.`, source: `Editorial example` },
  { text: `I love me, vol. I.`, source: `Editorial example` },
  { text: `If I had a hi-fi.`, source: `Editorial example` },
  { text: `Key lime, Emily, ek!`, source: `Editorial example` },
  { text: `Lace decal.`, source: `Editorial example` },
  { text: `Lager, sir, is regal.`, source: `Editorial example` },
  { text: `L.A. ocelots stole coal.`, source: `Editorial example` },
  { text: `Lap pal.`, source: `Editorial example` },
  { text: `Last egg gets Al!`, source: `Editorial example` },
  { text: `Lee has a race car as a heel.`, source: `Editorial example` },
  { text: `Lew, Otto has a hot towel.`, source: `Editorial example` },
  { text: `Liam was in a tub, but Ani saw mail.`, source: `Editorial example` },
  { text: `Lion oil.`, source: `Editorial example` },
  { text: `Live evil.`, source: `Editorial example` },
  { text: `Loot tool.`, source: `Editorial example` },
  { text: `Ma handed Edna ham.`, source: `Editorial example` },
  { text: `Ma is as selfless as I am.`, source: `Editorial example` },
  { text: `Mad at Adam.`, source: `Editorial example` },
  { text: `Marge lets Norah see Sharon's telegram.`, source: `Editorial example` },
  { text: `May a moody baby doom a yam?`, source: `Editorial example` },
  { text: `Mega gem.`, source: `Editorial example` },
  { text: `Mr. Owl ate my metal worm.`, source: `Editorial example` },
  { text: `Name tag gate man.`, source: `Editorial example` },
  { text: `Naomi, did I moan?`, source: `Editorial example` },
  { text: `Naomi, I moan.`, source: `Editorial example` },
  { text: `Neil A. sees alien!`, source: `Editorial example` },
  { text: `Neil, an alien?`, source: `Editorial example` },
  { text: `Net ten.`, source: `Editorial example` },
  { text: `Niagara, O roar again!`, source: `Editorial example` },
  { text: `No devil lived on.`, source: `Editorial example` },
  { text: `No lava on Avalon; no lava, no Avalon.`, source: `Editorial example` },
  { text: `No miss. It is Simon.`, source: `Editorial example` },
  { text: `No misses ordered roses, Simon.`, source: `Editorial example` },
  { text: `No panic, I nap on.`, source: `Editorial example` },
  { text: `Not a banana, baton!`, source: `Editorial example` },
  { text: `No way a papaya won!`, source: `Editorial example` },
  { text: `Now I see bees! I won!`, source: `Editorial example` },
  { text: `No X in Nixon.`, source: `Editorial example` },
  { text: `No, Mel, onward! Draw no lemon!`, source: `Editorial example` },
  { text: `No, sir! Away! A papaya war is on!`, source: `Editorial example` },
  { text: `No, son.`, source: `Editorial example` },
  { text: `Nola's salon.`, source: `Editorial example` },
  { text: `Not a ton.`, source: `Editorial example` },
  { text: `Not a tub, but a ton.`, source: `Editorial example` },
  { text: `Not New York, Roy went on.`, source: `Editorial example` },
  { text: `Now, sir, a war is won!`, source: `Editorial example` },
  { text: `Oh no, Don Ho!`, source: `Editorial example` },
  { text: `Oh, who was it I saw? Oh, who?`, source: `Editorial example` },
  { text: `OK, KO!`, source: `Editorial example` },
  { text: `One? No!`, source: `Editorial example` },
  { text: `Oozy rat in a sanitary zoo.`, source: `Editorial example` },
  { text: `O stone, be not so!`, source: `Editorial example` },
  { text: `Pals slap.`, source: `Editorial example` },
  { text: `Panic in a Titanic, I nap!`, source: `Editorial example` },
  { text: `Pa's a sap!`, source: `Editorial example` },
  { text: `Pat and Edna tap.`, source: `Editorial example` },
  { text: `Pets step.`, source: `Editorial example` },
  { text: `Poor Dan is in a droop.`, source: `Editorial example` },
  { text: `Pot top.`, source: `Editorial example` },
  { text: `Pull up, Eva! We're here! Wave! Pull up!`, source: `Editorial example` },
  { text: `Pupils, I say, as I slip up.`, source: `Editorial example` },
  { text: `Put a crow, a camel, a mini male macaw, or cat up.`, source: `Editorial example` },
  { text: `Race fast, safe car.`, source: `Editorial example` },
  { text: `Race vast, save car.`, source: `Editorial example` },
  { text: `Rat 'n' tar.`, source: `Editorial example` },
  { text: `Rats live on no evil star.`, source: `Editorial example` },
  { text: `Rats' star.`, source: `Editorial example` },
  { text: `Rise to vote, sir.`, source: `Editorial example` },
  { text: `Roy, am I mayor?`, source: `Editorial example` },
  { text: `Sages use gas.`, source: `Editorial example` },
  { text: `Senile felines.`, source: `Editorial example` },
  { text: `Sh! Tom sees moths.`, source: `Editorial example` },
  { text: `Sir, I soon saw Bob was no Osiris.`, source: `Editorial example` },
  { text: `Sir, I'm Iris.`, source: `Editorial example` },
  { text: `Sit on a potato pan, Otis.`, source: `Editorial example` },
  { text: `Slap a ham on Omaha, pals!`, source: `Editorial example` },
  { text: `Snack cans.`, source: `Editorial example` },
  { text: `Snug guns.`, source: `Editorial example` },
  { text: `Some men interpret nine memos.`, source: `Editorial example` },
  { text: `Stop racecar pots!`, source: `Editorial example` },
  { text: `Strap racecar parts.`, source: `Editorial example` },
  { text: `Straw warts.`, source: `Editorial example` },
  { text: `Stressed desserts.`, source: `Editorial example` },
  { text: `Stunt nuts!`, source: `Editorial example` },
  { text: `Swap paws.`, source: `Editorial example` },
  { text: `Ten animals I slam in a net.`, source: `Editorial example` },
  { text: `Todd erases a red dot.`, source: `Editorial example` },
  { text: `Too bad I hid a boot.`, source: `Editorial example` },
  { text: `Too fat a foot.`, source: `Editorial example` },
  { text: `Too hot to hoot.`, source: `Editorial example` },
  { text: `Trapeze part.`, source: `Editorial example` },
  { text: `UFO tofu.`, source: `Editorial example` },
  { text: `Warsaw was raw.`, source: `Editorial example` },
  { text: `War, sir, is raw.`, source: `Editorial example` },
  { text: `Was it a bar or a bat I saw?`, source: `Editorial example` },
  { text: `Was it a bat I saw?`, source: `Editorial example` },
  { text: `Was it a hat I saw?`, source: `Editorial example` },
  { text: `Was it a mat I saw?`, source: `Editorial example` },
  { text: `Was it a pat I saw?`, source: `Editorial example` },
  { text: `Was it a rat I saw?`, source: `Editorial example` },
  { text: `Was it a vat I saw?`, source: `Editorial example` },
  { text: `Was it Tim's mitt I saw?`, source: `Editorial example` },
  { text: `We panic in a pew.`, source: `Editorial example` },
  { text: `We sew.`, source: `Editorial example` },
  { text: `We'll let Dad tell Lew.`, source: `Editorial example` },
  { text: `Won't lovers revolt now?`, source: `Editorial example` },
  { text: `Wonton? Not now!`, source: `Editorial example` },
  { text: `Yawn a more Roman way.`, source: `Editorial example` },
  { text: `Yo! Banana boy!`, source: `Editorial example` },
  { text: `Yreka Bakery.`, source: `Editorial example` },
  { text: `Taco cat.`, source: `Editorial example` },
  { text: `Dennis sinned.`, source: `Editorial example` },
  { text: `Dennis and Edna sinned.`, source: `Editorial example` },
  { text: `Eva, can I see bees in a cave?`, source: `Editorial example` },
  { text: `Never even.`, source: `Editorial example` },
  { text: `Never ever even.`, source: `Editorial example` },
  { text: `Dr. Awkward.`, source: `Editorial example` },
  { text: `Mr. Alarm.`, source: `Editorial example` },
  { text: `Llama mall.`, source: `Editorial example` },
  { text: `So many dynamos!`, source: `Editorial example` },
] as const;

