import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../styles/theme/theme';

const createStyles = (palette: ThemePalette) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.page,
  },
  page: {
    flex: 1,
  },
  content: {
    paddingBottom: 0,
  },
  container: {
    width: `100%`,
    maxWidth: 1200,
    alignSelf: `center`,
    paddingHorizontal: 22,
  },
  header: {
    zIndex: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  headerInner: {
    paddingTop: 9,
    paddingBottom: 5,
  },
  headerBrandRow: {
    gap: 12,
    alignItems: `center`,
    flexDirection: `row`,
    justifyContent: `space-between`,
  },
  brand: {
    gap: 9,
    minHeight: 44,
    alignSelf: `flex-start`,
    alignItems: `center`,
    flexDirection: `row`,
  },
  brandName: {
    fontSize: 17,
    color: palette.ink,
    fontWeight: `600`,
    letterSpacing: -0.6,
  },
  themeToggle: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderRadius: 22,
    alignItems: `center`,
    borderColor: palette.lime,
    justifyContent: `center`,
    backgroundColor: palette.soft,
  },
  accountActions: {
    gap: 8,
    alignItems: `center`,
    flexDirection: `row`,
  },
  navigation: {
    gap: 18,
    alignItems: `center`,
    paddingVertical: 2,
  },
  navigationLink: {
    gap: 5,
    minHeight: 44,
    alignItems: `center`,
    flexDirection: `row`,
  },
  navigationText: {
    fontSize: 12,
    color: palette.muted,
  },
  signIn: {
    gap: 6,
    minHeight: 44,
    borderRadius: 22,
    paddingHorizontal: 16,
    alignItems: `center`,
    flexDirection: `row`,
    backgroundColor: palette.action,
  },
  signInText: {
    fontSize: 12,
    fontWeight: `600`,
    color: palette.page,
  },
  pressed: {
    opacity: 0.65,
  },
  hero: {
    overflow: `hidden`,
    position: `relative`,
    paddingTop: 32,
    paddingBottom: 54,
    alignItems: `center`,
  },
  heroLogo: {
    marginBottom: 30,
  },
  eyebrow: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: `600`,
    letterSpacing: 1.8,
    color: palette.action,
  },
  heroEyebrow: {
    textAlign: `center`,
    marginBottom: 16,
  },
  heroTitle: {
    fontSize: 49,
    lineHeight: 56,
    fontWeight: `600`,
    textAlign: `center`,
    color: palette.ink,
    letterSpacing: -2.6,
  },
  heroAccent: {
    color: palette.pink,
  },
  heroCopy: {
    fontSize: 14,
    maxWidth: 430,
    lineHeight: 24,
    marginTop: 19,
    textAlign: `center`,
    color: palette.muted,
  },
  search: {
    gap: 9,
    width: `100%`,
    maxWidth: 520,
    minHeight: 58,
    marginTop: 28,
    borderWidth: 1,
    borderRadius: 9,
    paddingVertical: 6,
    paddingRight: 6,
    paddingLeft: 14,
    alignItems: `center`,
    flexDirection: `row`,
    borderColor: palette.line,
    backgroundColor: palette.card,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    paddingVertical: 10,
    color: palette.ink,
  },
  searchButton: {
    gap: 6,
    minHeight: 44,
    borderRadius: 6,
    paddingHorizontal: 13,
    alignItems: `center`,
    flexDirection: `row`,
    backgroundColor: palette.lime,
  },
  searchButtonText: {
    fontSize: 12,
    fontWeight: `600`,
    color: palette.searchInk,
  },
  collection: {
    paddingTop: 28,
    paddingBottom: 56,
  },
  collectionHeading: {
    gap: 12,
    alignItems: `center`,
    flexDirection: `row`,
    justifyContent: `space-between`,
  },
  sectionTitle: {
    fontSize: 25,
    lineHeight: 33,
    fontWeight: `600`,
    color: palette.ink,
    letterSpacing: -0.8,
  },
  sampleLabel: {
    fontSize: 11,
    color: palette.muted,
  },
  collectionControls: {
    gap: 12,
    marginTop: 20,
    marginBottom: 18,
    alignItems: `center`,
    flexDirection: `row`,
    justifyContent: `space-between`,
  },
  filters: {
    gap: 2,
    alignItems: `center`,
    flexDirection: `row`,
  },
  filterButton: {
    minHeight: 40,
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    justifyContent: `center`,
  },
  filterSelected: {
    backgroundColor: palette.soft,
  },
  filterText: {
    fontSize: 12,
    color: palette.muted,
  },
  filterTextSelected: {
    color: palette.leaf,
    fontWeight: `600`,
  },
  sortButton: {
    gap: 5,
    minHeight: 40,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 10,
    alignItems: `center`,
    flexDirection: `row`,
    borderColor: palette.line,
  },
  sortText: {
    fontSize: 11,
    color: palette.muted,
  },
  grid: {
    gap: 18,
    flexWrap: `wrap`,
    flexDirection: `row`,
    alignItems: `flex-start`,
  },
  previewGrid: {
    alignItems: `center`,
    flexDirection: `column`,
  },
  widePreviewGrid: {
    flexDirection: `row`,
    justifyContent: `center`,
  },
  card: {
    width: `100%`,
    borderWidth: 1,
    borderRadius: 11,
    overflow: `hidden`,
    borderColor: palette.line,
    backgroundColor: palette.card,
  },
  wideCard: {
    flexGrow: 1,
    width: `48%`,
    maxWidth: `50%`,
  },
  threeColumnCard: {
    width: `31%`,
    maxWidth: `33%`,
  },
  previewCard: {
    maxWidth: 540,
    minHeight: 300,
  },
  widePreviewCard: {
    width: `28%`,
    maxWidth: `28%`,
  },
  previewNameCard: {
    maxWidth: 600,
    minHeight: 356,
  },
  widePreviewNameCard: {
    width: `35%`,
    maxWidth: `35%`,
  },
  cardContent: {
    paddingTop: 21,
    paddingBottom: 18,
    paddingHorizontal: 21,
  },
  previewCardContent: {
    flexGrow: 1,
  },
  previewNameContent: {
    paddingVertical: 30,
    paddingHorizontal: 24,
  },
  cardHeading: {
    gap: 8,
    flexWrap: `wrap`,
    alignItems: `center`,
    flexDirection: `row`,
    justifyContent: `space-between`,
  },
  topActions: {
    gap: 1,
    flexWrap: `wrap`,
    marginLeft: `auto`,
    alignItems: `center`,
    flexDirection: `row`,
    justifyContent: `flex-end`,
  },
  recordType: {
    borderRadius: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    alignSelf: `flex-start`,
    backgroundColor: palette.soft,
  },
  recordTypeText: {
    fontSize: 10,
    fontWeight: `500`,
    color: palette.leaf,
  },
  cardTitle: {
    fontSize: 34,
    lineHeight: 43,
    marginTop: 14,
    marginBottom: 10,
    fontWeight: `500`,
    color: palette.ink,
    letterSpacing: -1,
  },
  phraseTitle: {
    fontSize: 28,
    lineHeight: 37,
    letterSpacing: -0.8,
  },
  previewNameTitle: {
    fontSize: 40,
    lineHeight: 50,
    minHeight: 108,
    textAlign: `center`,
    textAlignVertical: `center`,
  },
  cardLanguage: {
    fontSize: 11,
    lineHeight: 18,
    color: palette.muted,
  },
  visibleMetadata: {
    gap: 12,
    marginTop: 21,
    flexWrap: `wrap`,
    flexDirection: `row`,
  },
  metadataPair: {
    gap: 5,
    flex: 1,
    minWidth: 72,
  },
  metadataLabel: {
    fontSize: 10,
    lineHeight: 15,
    color: palette.muted,
  },
  metadataValue: {
    fontSize: 11,
    lineHeight: 17,
    color: palette.ink,
  },
  cardFooter: {
    rowGap: 2,
    columnGap: 2,
    flexWrap: `wrap`,
    borderTopWidth: 1,
    paddingVertical: 5,
    paddingHorizontal: 12,
    alignItems: `center`,
    flexDirection: `row`,
    borderTopColor: palette.line,
  },
  detailsButton: {
    gap: 4,
    minHeight: 44,
    paddingHorizontal: 3,
    alignItems: `center`,
    flexDirection: `row`,
  },
  detailsText: {
    fontSize: 11,
    color: palette.muted,
  },
  chevronExpanded: {
    transform: [{ rotate: `180deg` }],
  },
  actions: {
    gap: 1,
    marginLeft: `auto`,
    alignItems: `center`,
    flexDirection: `row`,
  },
  iconButton: {
    width: 36,
    minHeight: 44,
    borderRadius: 5,
    alignItems: `center`,
    justifyContent: `center`,
  },
  commentButton: {
    gap: 4,
    width: `auto`,
    paddingHorizontal: 8,
    flexDirection: `row`,
  },
  actionCount: {
    fontSize: 11,
    color: palette.muted,
    fontVariant: [`tabular-nums`],
  },
  voteScore: {
    fontSize: 11,
    minWidth: 27,
    textAlign: `center`,
    color: palette.ink,
    fontVariant: [`tabular-nums`],
  },
  detailsPanel: {
    gap: 16,
    borderTopWidth: 1,
    paddingVertical: 18,
    paddingHorizontal: 21,
    borderTopColor: palette.line,
  },
  detailsMetadata: {
    gap: 16,
    flexDirection: `row`,
  },
  detailNote: {
    fontSize: 10,
    lineHeight: 17,
    color: palette.muted,
  },
  emptyState: {
    gap: 14,
    borderWidth: 1,
    borderRadius: 11,
    paddingVertical: 30,
    alignItems: `center`,
    paddingHorizontal: 22,
    borderColor: palette.line,
    backgroundColor: palette.card,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: `600`,
    color: palette.ink,
  },
  emptyCopy: {
    fontSize: 13,
    lineHeight: 22,
    textAlign: `center`,
    color: palette.muted,
  },
  browseButton: {
    gap: 7,
    minHeight: 44,
    marginTop: 23,
    alignSelf: `center`,
    alignItems: `center`,
    flexDirection: `row`,
  },
  browseText: {
    fontSize: 13,
    color: palette.action,
  },
  sampleNote: {
    fontSize: 10,
    lineHeight: 17,
    marginTop: 12,
    textAlign: `center`,
    color: palette.muted,
  },
  about: {
    paddingTop: 39,
    paddingBottom: 44,
    backgroundColor: palette.soft,
  },
  sectionCopy: {
    fontSize: 14,
    lineHeight: 25,
    marginTop: 14,
    color: palette.muted,
  },
  sectionEyebrow: {
    marginBottom: 11,
  },
  steps: {
    gap: 25,
    marginTop: 30,
  },
  step: {
    gap: 15,
    alignItems: `flex-start`,
    flexDirection: `row`,
  },
  stepNumber: {
    width: 35,
    fontSize: 12,
    lineHeight: 30,
    fontWeight: `600`,
    color: palette.leaf,
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    fontSize: 16,
    lineHeight: 28,
    fontWeight: `600`,
    color: palette.ink,
  },
  stepCopy: {
    fontSize: 13,
    lineHeight: 23,
    marginTop: 3,
    color: palette.muted,
  },
  section: {
    paddingTop: 52,
    paddingBottom: 6,
  },
  apiPanel: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 28,
    paddingHorizontal: 24,
    borderColor: palette.line,
    backgroundColor: palette.card,
  },
  apiIcon: {
    marginBottom: 17,
  },
  apiStatus: {
    gap: 6,
    marginTop: 19,
    alignItems: `center`,
    flexDirection: `row`,
  },
  apiStatusText: {
    fontSize: 11,
    fontWeight: `500`,
    color: palette.action,
  },
  faqItems: {
    marginTop: 19,
  },
  faqItem: {
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  faqQuestion: {
    gap: 14,
    minHeight: 64,
    paddingVertical: 17,
    alignItems: `center`,
    flexDirection: `row`,
    justifyContent: `space-between`,
  },
  faqQuestionText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: `500`,
    color: palette.ink,
  },
  faqAnswer: {
    fontSize: 13,
    lineHeight: 24,
    paddingBottom: 19,
    color: palette.muted,
  },
  contact: {
    paddingTop: 55,
    paddingBottom: 52,
  },
  contactButton: {
    gap: 8,
    minHeight: 46,
    marginTop: 22,
    borderRadius: 6,
    paddingHorizontal: 17,
    alignSelf: `flex-start`,
    alignItems: `center`,
    flexDirection: `row`,
    backgroundColor: palette.lime,
  },
  footer: {
    borderTopWidth: 1,
    paddingTop: 26,
    paddingBottom: 32,
    borderTopColor: palette.line,
  },
  footerBrand: {
    gap: 9,
    minHeight: 44,
    alignSelf: `flex-start`,
    alignItems: `center`,
    flexDirection: `row`,
  },
  footerBrandText: {
    fontSize: 13,
    fontWeight: `500`,
    color: palette.ink,
  },
  footerLinks: {
    gap: 25,
    marginTop: 5,
    flexDirection: `row`,
  },
  footerLink: {
    gap: 5,
    minHeight: 44,
    alignItems: `center`,
    flexDirection: `row`,
  },
  footerLinkText: {
    fontSize: 12,
    color: palette.muted,
  },
  copyright: {
    fontSize: 10,
    lineHeight: 19,
    marginTop: 18,
    color: palette.muted,
  },
  piratechs: {
    gap: 5,
    minHeight: 44,
    marginTop: 5,
    alignSelf: `flex-end`,
    alignItems: `center`,
    flexDirection: `row`,
  },
  piratechsText: {
    fontSize: 11,
    color: palette.muted,
  },
  scrollTop: {
    zIndex: 20,
    right: 19,
    width: 46,
    height: 46,
    borderWidth: 1,
    borderRadius: 23,
    position: `absolute`,
    borderColor: palette.line,
    backgroundColor: palette.card,
    shadowColor: palette.ink,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  scrollTopButton: {
    flex: 1,
    alignItems: `center`,
    justifyContent: `center`,
  },
  modalBackdrop: {
    flex: 1,
    padding: 24,
    alignItems: `center`,
    justifyContent: `center`,
    backgroundColor: `rgba(35, 38, 41, 0.3)`,
  },
  modalPanel: {
    width: `100%`,
    maxWidth: 430,
    borderWidth: 1,
    borderRadius: 13,
    paddingVertical: 24,
    paddingHorizontal: 24,
    borderColor: palette.line,
    backgroundColor: palette.card,
  },
  modalHeading: {
    gap: 12,
    alignItems: `center`,
    flexDirection: `row`,
    justifyContent: `space-between`,
  },
  modalTitle: {
    flex: 1,
    fontSize: 22,
    lineHeight: 29,
    fontWeight: `600`,
    color: palette.ink,
    letterSpacing: -0.6,
  },
  modalClose: {
    width: 44,
    height: 44,
    marginRight: -10,
    alignItems: `center`,
    justifyContent: `center`,
  },
  modalCopy: {
    fontSize: 14,
    lineHeight: 25,
    marginTop: 14,
    color: palette.muted,
  },
  modalConfirm: {
    gap: 8,
    minHeight: 44,
    marginTop: 24,
    borderRadius: 6,
    paddingHorizontal: 16,
    alignSelf: `flex-start`,
    alignItems: `center`,
    flexDirection: `row`,
    backgroundColor: palette.lime,
  },
  sortOptions: {
    gap: 6,
    marginTop: 18,
  },
  sortOption: {
    gap: 12,
    minHeight: 50,
    borderRadius: 7,
    paddingHorizontal: 13,
    alignItems: `center`,
    flexDirection: `row`,
  },
  sortOptionText: {
    flex: 1,
    fontSize: 14,
    color: palette.ink,
  },
});

export default createStyles;
