import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../styles/theme/theme';

const createStyles = (palette: ThemePalette) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.page },
  page: { flex: 1 },
  content: { flexGrow: 1 },
  container: { width: `100%`, maxWidth: 1200, alignSelf: `center`, paddingHorizontal: 22 },
  header: { zIndex: 10, borderBottomWidth: 1, borderBottomColor: palette.line },
  headerInner: { gap: 14, minHeight: 76, flexWrap: `wrap`, alignItems: `center`, paddingVertical: 10, flexDirection: `row`, justifyContent: `space-between` },
  brand: { gap: 8, minHeight: 44, alignItems: `center`, flexDirection: `row` },
  brandName: { fontSize: 17, fontWeight: `600`, color: palette.ink, letterSpacing: -0.6 },
  headerActions: { gap: 15, alignItems: `center`, flexDirection: `row` },
  themeToggle: { width: 42, height: 42, borderWidth: 1, borderRadius: 21, alignItems: `center`, borderColor: palette.lime, justifyContent: `center`, backgroundColor: palette.lime },
  textButton: { gap: 5, minHeight: 44, alignItems: `center`, flexDirection: `row` },
  linkText: { fontSize: 12, fontWeight: `600`, color: palette.ink },
  pressed: { opacity: 0.65 },
  layout: { gap: 34, flexGrow: 1, paddingTop: 28, paddingBottom: 44 },
  wideLayout: { gap: 70, alignItems: `center`, flexDirection: `row`, paddingVertical: 64 },
  story: { padding: 24, overflow: `hidden`, borderWidth: 1, borderRadius: 26, alignItems: `center`, borderColor: palette.line, backgroundColor: palette.card },
  wideStory: { flex: 1, minHeight: 600, paddingHorizontal: 35, justifyContent: `center` },
  eyebrow: { fontSize: 10, lineHeight: 16, fontWeight: `600`, color: palette.action, letterSpacing: 1.8 },
  art: { width: `100%`, height: 250, maxWidth: 350, marginVertical: 12, alignItems: `center`, justifyContent: `center` },
  orbit: { width: 176, height: 176, borderWidth: 1, borderRadius: 88, position: `absolute` },
  pinkOrbit: { top: 18, left: 0, opacity: 0.28, borderColor: palette.pink },
  greenOrbit: { right: 0, bottom: 12, opacity: 0.4, borderColor: palette.lime },
  artCardBack: { gap: 8, top: 24, right: 17, width: 224, height: 165, padding: 20, borderWidth: 1, borderRadius: 17, position: `absolute`, borderColor: palette.lime, backgroundColor: palette.soft, transform: [{ rotate: `9deg` }] },
  artBackText: { fontSize: 12, color: palette.leaf },
  artCard: { gap: 14, width: 255, maxWidth: `94%`, padding: 22, borderWidth: 1, borderRadius: 17, borderColor: palette.line, backgroundColor: palette.page, transform: [{ rotate: `-6deg` }] },
  artLabelRow: { gap: 7, alignItems: `center`, flexDirection: `row` },
  artLabel: { fontSize: 10, color: palette.muted },
  artWord: { fontSize: 47, lineHeight: 55, fontWeight: `600`, color: palette.ink, letterSpacing: -1.5 },
  artPhrase: { fontSize: 28, lineHeight: 35, letterSpacing: -0.7 },
  artDirection: { alignItems: `center`, flexDirection: `row`, justifyContent: `space-between` },
  reverseArrow: { transform: [{ rotate: `180deg` }] },
  storyTitle: { fontSize: 31, lineHeight: 38, fontWeight: `600`, textAlign: `center`, color: palette.ink, letterSpacing: -1.2 },
  storyAccent: { color: palette.pink },
  storyCopy: { fontSize: 13, maxWidth: 345, lineHeight: 23, marginTop: 14, textAlign: `center`, color: palette.muted },
  storyControls: { gap: 8, marginTop: 15, alignItems: `center`, flexDirection: `row` },
  iconButton: { width: 42, height: 44, alignItems: `center`, justifyContent: `center` },
  pagination: { alignItems: `center`, flexDirection: `row` },
  paginationButton: { width: 24, height: 44, alignItems: `center`, justifyContent: `center` },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: palette.line },
  activeDot: { width: 20, backgroundColor: palette.pink },
  formPanel: { width: `100%`, maxWidth: 470, alignSelf: `center` },
  wideFormPanel: { flex: 1 },
  steps: { gap: 8, marginBottom: 34, flexDirection: `row` },
  step: { gap: 8, flex: 1, alignItems: `center` },
  stepCircle: { width: 28, height: 28, borderWidth: 1, borderRadius: 14, alignItems: `center`, borderColor: palette.line, justifyContent: `center`, backgroundColor: palette.card },
  stepCircleActive: { borderColor: palette.lime, backgroundColor: palette.lime },
  stepNumber: { fontSize: 11, fontWeight: `600`, color: palette.muted },
  stepNumberActive: { color: palette.searchInk },
  stepLabel: { fontSize: 9, lineHeight: 14, textAlign: `center`, color: palette.muted },
  stepLabelActive: { fontWeight: `600`, color: palette.ink },
  formTitle: { fontSize: 32, lineHeight: 39, marginTop: 12, fontWeight: `600`, color: palette.ink, letterSpacing: -1.2 },
  formCopy: { fontSize: 13, lineHeight: 23, marginTop: 9, color: palette.muted },
  fields: { gap: 18, marginTop: 26 },
  field: { gap: 7 },
  labelRow: { gap: 8, minHeight: 25, alignItems: `center`, flexDirection: `row`, justifyContent: `space-between` },
  label: { fontSize: 12, fontWeight: `600`, color: palette.ink },
  inputWrap: { gap: 10, minHeight: 54, borderWidth: 1, borderRadius: 10, paddingLeft: 15, paddingRight: 4, alignItems: `center`, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.card },
  inputError: { borderColor: `#C94161` },
  input: { flex: 1, minWidth: 0, fontSize: 13, paddingVertical: 16, color: palette.ink },
  error: { fontSize: 11, lineHeight: 18, color: `#C94161` },
  hint: { fontSize: 11, lineHeight: 19, color: palette.muted },
  collectionOptions: { gap: 12, marginTop: 26 },
  interest: { gap: 13, padding: 16, minHeight: 83, borderWidth: 1, borderRadius: 13, alignItems: `center`, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.card },
  interestSelected: { borderColor: palette.lime, backgroundColor: palette.soft },
  interestIcon: { width: 33, alignItems: `center` },
  interestContent: { gap: 5, flex: 1 },
  interestTitle: { fontSize: 13, fontWeight: `600`, color: palette.ink },
  interestExample: { fontSize: 11, fontWeight: `400`, color: palette.muted },
  interestCopy: { fontSize: 11, lineHeight: 18, color: palette.muted },
  checkbox: { width: 20, height: 20, borderWidth: 1, borderRadius: 6, alignItems: `center`, borderColor: palette.line, justifyContent: `center` },
  checkboxSelected: { borderColor: palette.lime, backgroundColor: palette.lime },
  privacyNote: { gap: 10, marginTop: 5, paddingVertical: 12, alignItems: `center`, flexDirection: `row` },
  privacyCopy: { flex: 1 },
  summary: { gap: 8, padding: 25, marginTop: 26, borderWidth: 1, borderRadius: 15, alignItems: `center`, borderColor: palette.line, backgroundColor: palette.card },
  readyIcon: { width: 62, height: 62, borderRadius: 31, marginBottom: 6, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.lime },
  summaryName: { fontSize: 20, fontWeight: `600`, color: palette.ink },
  summaryInterests: { gap: 8, marginVertical: 10, flexWrap: `wrap`, alignItems: `center`, flexDirection: `row`, justifyContent: `center` },
  summaryChip: { gap: 5, borderRadius: 20, paddingVertical: 8, paddingHorizontal: 12, alignItems: `center`, flexDirection: `row`, backgroundColor: palette.soft },
  summaryChipText: { fontSize: 11, color: palette.leaf },
  notice: { fontSize: 12, lineHeight: 21, padding: 13, marginTop: 20, borderRadius: 10, color: palette.leaf, backgroundColor: palette.soft },
  formActions: { gap: 14, marginTop: 22, alignItems: `center`, flexDirection: `row` },
  backButton: { gap: 7, minHeight: 52, paddingRight: 7, alignItems: `center`, flexDirection: `row` },
  primaryButton: { gap: 9, flex: 1, minHeight: 52, borderRadius: 10, alignItems: `center`, flexDirection: `row`, justifyContent: `center`, backgroundColor: palette.lime },
  primaryButtonText: { fontSize: 13, fontWeight: `600`, color: palette.searchInk },
  divider: { gap: 14, marginVertical: 20, alignItems: `center`, flexDirection: `row` },
  dividerLine: { flex: 1, height: 1, backgroundColor: palette.line },
  googleButton: { gap: 10, minHeight: 52, borderWidth: 1, borderRadius: 10, alignItems: `center`, flexDirection: `row`, borderColor: palette.line, justifyContent: `center`, backgroundColor: palette.card },
  googleButtonText: { fontSize: 13, fontWeight: `500`, color: palette.ink },
  modeSwitch: { gap: 7, marginTop: 14, flexWrap: `wrap`, alignItems: `center`, flexDirection: `row`, justifyContent: `center` },
  accountHint: { fontSize: 10, lineHeight: 18, marginTop: 16, textAlign: `center`, color: palette.muted },
  footer: { borderTopWidth: 1, paddingTop: 12, borderTopColor: palette.line },
  footerInner: { gap: 5, alignItems: `center`, justifyContent: `space-between` },
  copyright: { fontSize: 10, lineHeight: 18, color: palette.muted },
  footerLinks: { gap: 18, flexWrap: `wrap`, alignItems: `center`, flexDirection: `row`, justifyContent: `center` },
  scrollTop: { right: 19, width: 46, height: 46, borderWidth: 1, borderRadius: 23, position: `absolute`, borderColor: palette.line, backgroundColor: palette.lime },
  scrollTopButton: { flex: 1, alignItems: `center`, justifyContent: `center` },
});

export default createStyles;
