import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../styles/theme/theme';

const createStyles = (palette: ThemePalette) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.page },
  page: { flex: 1 },
  content: { flexGrow: 1 },
  container: { width: `100%`, maxWidth: 1200, alignSelf: `center`, paddingHorizontal: 22 },
  header: { zIndex: 10, borderBottomWidth: 1, borderBottomColor: palette.line },
  headerInner: { gap: 14, minHeight: 76, flexWrap: `wrap`, alignItems: `center`, paddingVertical: 10, flexDirection: `row`, justifyContent: `space-between` },
  brand: { gap: 8, minHeight: 44, alignItems: `center`, flexDirection: `row` },
  brandName: { fontSize: 17, fontWeight: `600`, color: palette.ink, letterSpacing: -0.6 },
  headerActions: { gap: 15, alignItems: `center`, flexDirection: `row` },
  themeToggle: { width: 42, height: 42, borderWidth: 1, borderRadius: 21, alignItems: `center`, borderColor: palette.lime, justifyContent: `center`, backgroundColor: palette.lime },
  textButton: { gap: 6, minHeight: 44, alignItems: `center`, flexDirection: `row` },
  linkText: { fontSize: 12, fontWeight: `600`, color: palette.ink },
  pressed: { opacity: 0.65 },
  main: { flexGrow: 1, paddingBottom: 64 },
  hero: { gap: 17, paddingTop: 48, paddingBottom: 43, alignItems: `center` },
  eyebrowRow: { gap: 8, alignItems: `center`, flexDirection: `row` },
  eyebrow: { fontSize: 10, lineHeight: 17, fontWeight: `600`, color: palette.action, letterSpacing: 1.8 },
  heroTitle: { fontSize: 46, lineHeight: 54, fontWeight: `600`, color: palette.ink, textAlign: `center`, letterSpacing: -1.8 },
  smallHeroTitle: { fontSize: 34, lineHeight: 41, letterSpacing: -1.3 },
  heroAccent: { color: palette.pink },
  heroCopy: { fontSize: 14, maxWidth: 560, lineHeight: 24, color: palette.muted, textAlign: `center` },
  layout: { gap: 30 },
  wideLayout: { gap: 45, alignItems: `flex-start`, flexDirection: `row` },
  supportPanel: { gap: 12 },
  wideSupportPanel: { flex: 0.8, paddingTop: 17 },
  sectionTitle: { fontSize: 25, lineHeight: 33, fontWeight: `600`, color: palette.ink, letterSpacing: -0.7 },
  copy: { fontSize: 12, lineHeight: 22, color: palette.muted },
  guides: { gap: 25, marginTop: 10 },
  guide: { gap: 13, flexDirection: `row` },
  guideIcon: { width: 42, height: 42, borderWidth: 1, borderRadius: 13, alignItems: `center`, borderColor: palette.line, justifyContent: `center`, backgroundColor: palette.card },
  guideContent: { gap: 6, flex: 1, paddingTop: 2 },
  guideTitle: { fontSize: 13, lineHeight: 21, fontWeight: `600`, color: palette.ink },
  piratechsCard: { gap: 9, padding: 21, marginTop: 13, borderWidth: 1, borderRadius: 17, borderColor: palette.line, backgroundColor: palette.soft },
  formCard: { gap: 23, padding: 30, borderWidth: 1, borderRadius: 24, borderColor: palette.line, backgroundColor: palette.card },
  wideFormCard: { flex: 1.4 },
  smallFormCard: { padding: 20 },
  formHeading: { gap: 13, alignItems: `flex-start`, flexDirection: `row` },
  formTitleIcon: { width: 45, height: 45, borderRadius: 14, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.page },
  formTitleContent: { gap: 7, flex: 1 },
  formTitle: { fontSize: 23, lineHeight: 30, fontWeight: `600`, color: palette.ink, letterSpacing: -0.6 },
  fields: { gap: 21 },
  identityFields: { gap: 19 },
  wideIdentityFields: { gap: 16, flexDirection: `row` },
  identityColumn: { flex: 1 },
  field: { gap: 8 },
  labelRow: { gap: 8, alignItems: `center`, flexDirection: `row` },
  label: { fontSize: 12, fontWeight: `600`, color: palette.ink },
  optional: { fontSize: 10, color: palette.muted },
  inputWrap: { gap: 10, minHeight: 53, borderWidth: 1, borderRadius: 10, paddingHorizontal: 14, alignItems: `center`, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.page },
  inputError: { borderColor: `#C94161` },
  input: { flex: 1, minWidth: 0, fontSize: 13, paddingVertical: 15, color: palette.ink },
  messageWrap: { alignItems: `flex-start` },
  messageIcon: { paddingTop: 17 },
  messageInput: { minHeight: 155, textAlignVertical: `top`, lineHeight: 22 },
  messageDetails: { gap: 10, flexWrap: `wrap`, flexDirection: `row`, justifyContent: `space-between` },
  error: { fontSize: 11, lineHeight: 18, color: `#C94161` },
  hint: { fontSize: 11, lineHeight: 19, color: palette.muted },
  topicOptions: { gap: 8, flexWrap: `wrap`, flexDirection: `row` },
  topic: { gap: 7, minHeight: 44, borderWidth: 1, borderRadius: 10, paddingVertical: 10, paddingHorizontal: 12, alignItems: `center`, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.page },
  topicSelected: { borderColor: palette.lime, backgroundColor: palette.soft },
  topicLabel: { fontSize: 11, color: palette.ink },
  topicLabelSelected: { fontWeight: `600` },
  previewNotice: { gap: 11, padding: 15, borderWidth: 1, borderRadius: 12, alignItems: `flex-start`, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.soft },
  noticeContent: { gap: 3, flex: 1 },
  noticeTitle: { fontSize: 12, lineHeight: 19, fontWeight: `600`, color: palette.ink },
  validatedResult: { gap: 12, padding: 16, borderWidth: 1, borderRadius: 12, alignItems: `center`, flexDirection: `row`, borderColor: palette.lime, backgroundColor: palette.soft },
  readyIcon: { width: 36, height: 36, borderRadius: 18, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.lime },
  formActions: { gap: 17, flexWrap: `wrap`, alignItems: `center`, flexDirection: `row` },
  primaryButton: { gap: 9, flex: 1, minWidth: 170, minHeight: 52, borderRadius: 10, alignItems: `center`, flexDirection: `row`, justifyContent: `center`, backgroundColor: palette.lime },
  primaryButtonText: { fontSize: 13, fontWeight: `600`, color: palette.searchInk },
  resetButton: { gap: 7, minHeight: 48, alignItems: `center`, flexDirection: `row` },
  privacyNote: { gap: 7, alignItems: `center`, flexDirection: `row`, flexWrap: `wrap` },
  faq: { gap: 12, width: `100%`, maxWidth: 780, marginTop: 57, alignSelf: `center` },
  questions: { marginTop: 8, borderWidth: 1, borderRadius: 16, overflow: `hidden`, borderColor: palette.line, backgroundColor: palette.card },
  question: { borderBottomWidth: 1, borderBottomColor: palette.line },
  questionToggle: { gap: 12, minHeight: 63, paddingVertical: 17, paddingHorizontal: 19, alignItems: `center`, flexDirection: `row` },
  questionTitle: { flex: 1, fontSize: 13, lineHeight: 21, fontWeight: `600`, color: palette.ink },
  expandedChevron: { transform: [{ rotate: `180deg` }] },
  answer: { fontSize: 12, lineHeight: 22, paddingLeft: 48, paddingRight: 22, paddingBottom: 20, color: palette.muted },
  footer: { borderTopWidth: 1, paddingTop: 12, borderTopColor: palette.line },
  footerInner: { gap: 5, alignItems: `center`, justifyContent: `space-between` },
  copyright: { fontSize: 10, lineHeight: 18, color: palette.muted },
  footerLinks: { gap: 18, flexWrap: `wrap`, alignItems: `center`, flexDirection: `row`, justifyContent: `center` },
  scrollTop: { right: 19, width: 46, height: 46, borderWidth: 1, borderRadius: 23, position: `absolute`, borderColor: palette.line, backgroundColor: palette.lime },
  scrollTopButton: { flex: 1, alignItems: `center`, justifyContent: `center` },
});

export default createStyles;
