import { Platform, StyleSheet } from 'react-native';
import type { ThemePalette } from '../../styles/theme/theme';

const createStyles = (palette: ThemePalette) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.page,
  },
  page: {
    flex: 1,
  },
  content: {
    paddingBottom: 0,
  },
  container: {
    width: `100%`,
    maxWidth: 1040,
    alignSelf: `center`,
    paddingHorizontal: 22,
  },
  header: {
    zIndex: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  headerInner: {
    maxWidth: 1200,
    paddingTop: 9,
    paddingBottom: 5,
  },
  brandRow: {
    gap: 12,
    alignItems: `center`,
    flexDirection: `row`,
    justifyContent: `space-between`,
  },
  brand: {
    gap: 9,
    minHeight: 44,
    alignSelf: `flex-start`,
    alignItems: `center`,
    flexDirection: `row`,
  },
  brandName: {
    fontSize: 17,
    color: palette.ink,
    fontWeight: `600`,
    letterSpacing: -0.6,
  },
  themeToggle: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderRadius: 22,
    alignItems: `center`,
    borderColor: palette.lime,
    justifyContent: `center`,
    backgroundColor: palette.soft,
  },
  accountActions: {
    gap: 8,
    alignItems: `center`,
    flexDirection: `row`,
  },
  signIn: {
    gap: 6,
    minHeight: 44,
    borderRadius: 22,
    paddingHorizontal: 16,
    alignItems: `center`,
    flexDirection: `row`,
    backgroundColor: palette.action,
  },
  signInText: {
    fontSize: 12,
    fontWeight: `600`,
    color: palette.page,
  },
  navigation: {
    gap: 18,
    alignItems: `center`,
    paddingVertical: 2,
  },
  navigationLink: {
    gap: 5,
    minHeight: 44,
    alignItems: `center`,
    flexDirection: `row`,
  },
  navigationText: {
    fontSize: 12,
    color: palette.muted,
  },
  activeText: {
    color: palette.action,
  },
  pressed: {
    opacity: 0.65,
  },
  hero: {
    paddingTop: 20,
    paddingBottom: 38,
  },
  breadcrumb: {
    gap: 7,
    minHeight: 34,
    marginBottom: 24,
    alignSelf: `flex-start`,
    alignItems: `center`,
    flexDirection: `row`,
  },
  breadcrumbText: {
    fontSize: 11,
    lineHeight: 18,
    color: palette.muted,
  },
  eyebrow: {
    fontSize: 10,
    lineHeight: 16,
    marginBottom: 14,
    fontWeight: `600`,
    letterSpacing: 1.8,
    color: palette.action,
  },
  title: {
    fontSize: 38,
    maxWidth: 780,
    lineHeight: 43,
    color: palette.ink,
    fontWeight: `600`,
    letterSpacing: -1.6,
  },
  description: {
    fontSize: 14,
    marginTop: 19,
    maxWidth: 680,
    lineHeight: 26,
    color: palette.muted,
  },
  examples: {
    marginBottom: 41,
  },
  examplesCopy: {
    fontSize: 12,
    marginTop: 9,
    lineHeight: 21,
    color: palette.muted,
  },
  exampleGrid: {
    gap: 15,
    marginTop: 23,
  },
  example: {
    padding: 23,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: palette.line,
    backgroundColor: palette.card,
  },
  exampleHeading: {
    gap: 17,
    alignItems: `center`,
    flexDirection: `row`,
    justifyContent: `space-between`,
  },
  exampleTitle: {
    flex: 1,
    fontSize: 23,
    lineHeight: 31,
    color: palette.ink,
    fontWeight: `600`,
    letterSpacing: -0.6,
  },
  exampleCount: {
    fontSize: 10,
    marginTop: 10,
    lineHeight: 17,
    color: palette.action,
  },
  exampleNote: {
    fontSize: 12,
    marginTop: 13,
    lineHeight: 22,
    color: palette.muted,
  },
  reading: {
    maxWidth: 760,
  },
  section: {
    paddingBottom: 29,
  },
  sectionSeparated: {
    paddingTop: 27,
    borderTopWidth: 1,
    borderTopColor: palette.line,
  },
  sectionTitle: {
    fontSize: 23,
    lineHeight: 31,
    color: palette.ink,
    fontWeight: `600`,
    letterSpacing: -0.6,
  },
  paragraph: {
    fontSize: 13,
    marginTop: 17,
    lineHeight: 25,
    color: palette.muted,
  },
  bulletRow: {
    gap: 10,
    marginTop: 12,
    alignItems: `flex-start`,
    flexDirection: `row`,
  },
  bulletMarker: {
    fontSize: 14,
    lineHeight: 25,
    color: palette.action,
  },
  bulletText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 25,
    color: palette.muted,
  },
  code: {
    marginTop: 22,
    borderWidth: 1,
    borderRadius: 9,
    borderColor: palette.line,
    backgroundColor: palette.soft,
  },
  codeContent: {
    padding: 20,
  },
  codeText: {
    fontSize: 11,
    lineHeight: 21,
    color: palette.leaf,
    fontFamily: Platform.OS === `ios` ? `Courier` : `monospace`,
  },
  links: {
    gap: 5,
    marginTop: 14,
    alignItems: `flex-start`,
  },
  textLink: {
    gap: 7,
    minHeight: 42,
    alignItems: `center`,
    flexDirection: `row`,
  },
  linkLabel: {
    fontSize: 12,
    color: palette.action,
  },
  related: {
    marginTop: 12,
    paddingTop: 26,
    paddingBottom: 20,
    backgroundColor: palette.soft,
  },
  relatedTitle: {
    fontSize: 21,
    lineHeight: 29,
    color: palette.leaf,
    fontWeight: `600`,
    letterSpacing: -0.6,
  },
  relatedNavigation: {
    gap: 20,
    marginTop: 13,
    flexWrap: `wrap`,
    flexDirection: `row`,
  },
  footer: {
    marginTop: 48,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: palette.line,
  },
  footerBrandName: {
    fontSize: 14,
    color: palette.ink,
    fontWeight: `600`,
    letterSpacing: -0.4,
  },
  footerNavigation: {
    gap: 3,
    marginTop: 10,
    flexWrap: `wrap`,
    columnGap: 20,
    flexDirection: `row`,
  },
  footerBottom: {
    gap: 6,
    marginTop: 14,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: palette.line,
  },
  copyright: {
    fontSize: 10,
    lineHeight: 18,
    color: palette.muted,
  },
  piratechsLink: {
    gap: 7,
    minHeight: 34,
    alignSelf: `flex-end`,
    alignItems: `center`,
    flexDirection: `row`,
  },
  scrollTop: {
    right: 22,
    position: `absolute`,
  },
  scrollTopButton: {
    width: 44,
    height: 44,
    borderRadius: 9,
    alignItems: `center`,
    justifyContent: `center`,
    backgroundColor: palette.lime,
  },
});

export default createStyles;
