import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../styles/theme/theme';

const createStyles = (palette: ThemePalette) => StyleSheet.create({
  section: {
    paddingTop: 66,
    paddingBottom: 30,
  },
  pageSection: {
    paddingTop: 0,
  },
  container: {
    width: `100%`,
    maxWidth: 1200,
    alignSelf: `center`,
    paddingHorizontal: 22,
  },
  heading: {
    maxWidth: 620,
    marginBottom: 30,
    alignSelf: `center`,
  },
  eyebrow: {
    fontSize: 10,
    lineHeight: 16,
    marginBottom: 11,
    letterSpacing: 1.8,
    fontWeight: `600`,
    textAlign: `center`,
    color: palette.action,
  },
  title: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: `600`,
    color: palette.ink,
    textAlign: `center`,
    letterSpacing: -1.2,
  },
  description: {
    fontSize: 14,
    marginTop: 12,
    lineHeight: 24,
    textAlign: `center`,
    color: palette.muted,
  },
  table: {
    borderWidth: 1,
    flexWrap: `wrap`,
    borderRadius: 14,
    overflow: `hidden`,
    flexDirection: `row`,
    borderColor: palette.line,
    backgroundColor: palette.card,
  },
  plan: {
    padding: 21,
    paddingTop: 28,
    minHeight: 548,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    position: `relative`,
    borderColor: palette.line,
  },
  lastColumn: {
    borderRightWidth: 0,
  },
  lastRow: {
    borderBottomWidth: 0,
  },
  highlightedPlan: {
    backgroundColor: palette.soft,
  },
  folderTab: {
    top: 0,
    left: 21,
    width: 46,
    height: 6,
    position: `absolute`,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
  },
  audience: {
    fontSize: 9,
    lineHeight: 16,
    minHeight: 16,
    letterSpacing: 1.1,
    fontWeight: `600`,
    color: palette.muted,
    textTransform: `uppercase`,
  },
  markRow: {
    gap: 8,
    marginTop: 16,
    minHeight: 36,
    marginBottom: 9,
    flexDirection: `row`,
    alignItems: `center`,
    justifyContent: `space-between`,
  },
  badge: {
    fontSize: 9,
    flexShrink: 1,
    lineHeight: 15,
    borderWidth: 1,
    borderRadius: 5,
    fontWeight: `600`,
    color: palette.leaf,
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderColor: palette.lime,
  },
  planName: {
    fontSize: 25,
    lineHeight: 33,
    fontWeight: `600`,
    letterSpacing: -0.7,
  },
  summary: {
    fontSize: 12,
    marginTop: 9,
    minHeight: 58,
    lineHeight: 20,
    color: palette.muted,
  },
  priceRow: {
    gap: 7,
    minHeight: 47,
    marginTop: 16,
    flexDirection: `row`,
    alignItems: `baseline`,
  },
  price: {
    fontSize: 39,
    lineHeight: 47,
    fontWeight: `600`,
    color: palette.ink,
    letterSpacing: -1.3,
  },
  period: {
    fontSize: 11,
    lineHeight: 18,
    color: palette.muted,
  },
  detail: {
    fontSize: 11,
    marginTop: 5,
    minHeight: 34,
    lineHeight: 17,
    color: palette.muted,
  },
  features: {
    gap: 13,
    flexGrow: 1,
    marginTop: 20,
    paddingTop: 21,
    borderTopWidth: 1,
    marginBottom: 25,
    borderTopColor: palette.line,
  },
  feature: {
    gap: 9,
    flexDirection: `row`,
    alignItems: `flex-start`,
  },
  featureLabel: {
    flex: 1,
    fontSize: 12,
    lineHeight: 19,
    color: palette.ink,
  },
  action: {
    gap: 9,
    minHeight: 44,
    borderWidth: 1,
    borderRadius: 7,
    paddingVertical: 11,
    paddingHorizontal: 10,
    flexDirection: `row`,
    alignItems: `center`,
    borderColor: palette.line,
    justifyContent: `center`,
    backgroundColor: palette.page,
  },
  highlightedAction: {
    borderColor: palette.lime,
    backgroundColor: palette.lime,
  },
  actionLabel: {
    fontSize: 11,
    lineHeight: 18,
    fontWeight: `600`,
    color: palette.ink,
  },
  highlightedActionLabel: {
    color: palette.searchInk,
  },
  pressed: {
    opacity: 0.65,
  },
  planFooter: {
    gap: 9,
    marginTop: 21,
    paddingTop: 14,
    borderTopWidth: 1,
    flexDirection: `row`,
    alignItems: `center`,
    borderTopColor: palette.line,
    justifyContent: `space-between`,
  },
  number: {
    fontSize: 10,
    lineHeight: 17,
    color: palette.muted,
    fontVariant: [`tabular-nums`],
  },
  status: {
    fontSize: 10,
    lineHeight: 17,
    color: palette.muted,
  },
  note: {
    gap: 8,
    maxWidth: 700,
    marginTop: 21,
    alignSelf: `center`,
    flexDirection: `row`,
    alignItems: `flex-start`,
    justifyContent: `center`,
  },
  noteLabel: {
    fontSize: 11,
    flexShrink: 1,
    lineHeight: 18,
    textAlign: `center`,
    color: palette.muted,
  },
});

export default createStyles;
